name: Build and run tests
on: [ 'push' ]
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        build_type: [Debug, Release]
        cxx_standard: [14, 17, 20, 23, 26]
        exclude:
        - os: windows-latest
          cxx_standard: 23
        - os: macos-latest
          cxx_standard: 26
        - os: ubuntu-latest
          cxx_standard: 26
    env:
      PREFIX: ${{ github.workspace }}/_local
    steps:
      # Check out project
      - uses: actions/checkout@v4
      # Check out dependencies
      - uses: actions/checkout@v4
        with:
          repository: google/googletest
          ref: 8d51dc50eb7e7698427fed81b85edad0e032112e
          path: googletest
      # Manually install dependencies
      - name: Install Google Test
        run: |
          cmake -S googletest -B build/deps/googletest -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_INSTALL_PREFIX=${{ env.PREFIX }}' -DBUILD_GMOCK=OFF -DBUILD_SHARED_LIBS=ON
          cmake --build build/deps/googletest --config RelWithDebInfo --target install
      # Build and test project
      - name: CMake Configure
        run: >
          cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_PREFIX_PATH=${{ env.PREFIX }}' -DCMAKE_CXX_STANDARD=${{ matrix.cxx_standard }}
      - name: CMake Build
        run: cmake --build build --config RelWithDebInfo
      - name: CTest
        run: ctest --test-dir build
